### ISSUE TITLE
ImportError: cannot import name 'cached_property' from 'werkzeug'

### ISSUE THREAD

**Issue by pooladkhay** [OtchereDev/coursehunter-video-downloader#14]
I get this Error when trying to run main.py:

```
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from module.extractor import extract_video, extract_video_url
  File "/Users/mamad/Downloads/coursehunter-video-downloader/module/extractor/extract_video_url.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/Users/mamad/Library/Python/3.8/lib/python/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/Users/mamad/Library/Python/3.8/lib/python/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/Users/mamad/Library/Python/3.8/lib/python/site-packages/werkzeug/__init__.py)
FAIL: 1
```

**Comment by OtchereDev** [comment]
Sorry for that issue but this has been some already in #3, please check the solution that was given there.... Please don't forget to leave me a 🌟 to help others find this project.
