### ISSUE TITLE
it won't work

### ISSUE THREAD

**Issue by parcpaes** [OtchereDev/coursehunter-video-downloader#15]
python3 main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from module.extractor import extract_video, extract_video_url
  File "../Documents/coursehunter-video-downloader/module/extractor/extract_video_url.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "../.local/lib/python3.8/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "../.local/lib/python3.8/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (../.local/lib/python3.8/site-packages/werkzeug/__init__.py)

python2 main.py
File "main.py", line 13
    print(f'{Fore.GREEN}+++++++++++++++++++++++++++++++++++++++++++++++++++{Style.RESET_ALL}')
                                                                                            ^
SyntaxError: invalid syntax
I'm not sure but I installed pip3 and then pip 20.2.4 on ubuntu 20.0.4
it works 
pip install --upgrade Werkzeug==0.16.0

**Comment by OtchereDev** [comment]
Hoping it is working for you now.... Don't forget to leave 🌟... Thank you
