### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Morb0** [OtchereDev/coursehunter-video-downloader#17]
Python 3.9.1

use `py main.py`
got error:
<pre>
Traceback (most recent call last):
  File "...\coursehunter-video-downloader\main.py", line 3, in <module>
    from module.extractor import extract_video, extract_video_url
  File "...\coursehunter-video-downloader\module\extractor\extract_video_url.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\robobrowser\__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\robobrowser\browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (...\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\__init__.py)
</pre>

**Comment by Morb0** [comment]
#3 fix this, i think this need write in README as this is a common error
